# Generated by Django 6.0.1 on 2026-02-03 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_api', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day', models.IntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('target_cal', models.FloatField()),
                ('chosen_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in', to='food_api.food')),
                ('food_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shown_as_1', to='food_api.food')),
                ('food_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shown_as_2', to='food_api.food')),
                ('food_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shown_as_3', to='food_api.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_interactions', to='user.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'day'], name='meal_intera_user_id_fa860f_idx'), models.Index(fields=['meal_type', 'day'], name='meal_intera_meal_ty_d2e9a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day', 'meal_type'), name='unique_user_day_meal')],
            },
        ),
    ]
