# Generated by Django 5.0.14 on 2026-02-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_interaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mealinteraction',
            name='unique_user_day_meal',
        ),
        migrations.RemoveIndex(
            model_name='mealinteraction',
            name='meal_intera_user_id_fa860f_idx',
        ),
        migrations.RemoveIndex(
            model_name='mealinteraction',
            name='meal_intera_meal_ty_d2e9a7_idx',
        ),
    ]
