# Generated by Django 5.0.14 on 2026-02-13 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_interaction', '0002_remove_mealinteraction_unique_user_day_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealinteraction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
