# Generated by Django 6.0.1 on 2026-02-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
